application: workwithme12
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /_ah/login_required
  script: do_openid_login.py
  
- url: /JS
  static_dir: JS

- url: /images
  static_dir: images
  
- url: /test
  static_dir: test

- url: /profile
  script: home.py
  
- url: /conversation/.*
  script: home.py
  login: required

- url: /.*
  script: home.py
